### ISSUE TITLE
Adjust StreamStats routing rules for NSS Services Documentation

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/NSSServicesDocumentation#2]
We've created NSS Services Documentation pages to describe our NSS Service Endpoints for general use.
The goal is for them to be served in a similar manner the StreamStats Services documentation is.
(StreamStats service documentation URL here: https://streamstats.usgs.gov/streamstatsservices/#/ )

For reference StreamStats routing rules:
https://docs.google.com/document/d/1yNX3Z4T5fm3DvuAbw8x0ZjpZOFD1ltYrNoGGCd6ljag/edit?usp=sharing

NSS Service Documentation has been deployed for test - bucket path here:
http://test.streamstats.usgs.gov.s3-website-us-east-1.amazonaws.com/nssservices/

**Comment by aaronstephenson** [comment]
Sorry, this has languished in triage because no one was assigned and I haven't been looking very closely. Is this still needed?

**Comment by jknewson** [comment]
No, I think I took took care of it. I'll close it.
